### ISSUE TITLE
State value not visible in job detail

### ISSUE THREAD

**Issue by SukhmeetSingh2002** [cdpc-iitrpr/cdpc-recruiter-frontend#2]
When we navigate next and come back the values stored in `jafJobDetails` is not shown in the fields

Fix:
add value to the field as following
![code](https://github.com/cdpc-iitrpr/cdpc-recruiter-frontend/assets/78161187/961af83b-6069-407a-b5a6-c539b2e83283)

**Comment by SukhmeetSingh2002** [comment]
Fixed

**Comment by pranav-mallela** [comment]
Dear Sukhmeet,

Thank you for closing Issue #2 as completed. I appreciate your prompt
response and action on this matter.

Best regards,
Pranav
